global:
  scrape_interval: 5s

scrape_configs:
  - job_name: spring-boot
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app-1:8080', 'app-2:8080']

  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: envoy
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ['grpc-lb:9901']
